name: "Hello"
description: "Send messages to Slack Channel from github action"

inputs:
  slackSignInSecret: 
    description: 'Slack Signing Secret from App Credentials (Slack Basic Information)'
    required: true
  slackBotToken: 
    description: 'Slack Bot User OAuth Token (Slack OAuth & Permissions)'
    required: true

runs:
  using: "node20"
  main: "dist/index.js"