name: Run my action

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    name: Checks if this action works
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Custom action run
      uses: ./
      with: 
        slackSignInSecret: ${{ secrets.SLACK_SIGNIN_SECRET }}
        slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}